import Sidebar from '@/components/surface/Sidebar/index'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='bg-gray-900 text-white flex max-h-screen h-screen'>
        <Sidebar/>
        {children}
      </body>
    </html>
  )
}
